version: '2'
services:
  green:
    restart: "always"
    build: 
      context: .
      args:
        string: green
    ports:
     - "9898:80"
    image: busroskilde
    environment:
      TZ: "Europe/Amsterdam"
  blue:
    restart: "always"
    build:
      context: .
      args:
        string: blue
    ports:
     - "9899:80"
    image: busroskilde
    environment:
      TZ: "Europe/Amsterdam"